runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: images
- url: /style
  static_dir: style
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
